title: My GameObject does not show my new material
hero_image: images/banner.png
description: My GameObject does not show my new material
version: 4
listed: false
copyedit: false
last_tested: "2021-11-23"
steps:
  - 
    title: My GameObject does not show my new material
